seed_everything: null
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  gpus: 1
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  accumulate_grad_batches: null
  max_epochs: 500
  log_every_n_steps: 50
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  reload_dataloaders_every_n_epochs: 0
  detect_anomaly: true
  move_metrics_to_cpu: false
model:
  feat: _ABS_DATAFLOW_datatype_all
  num_layers: 5
  num_mlp_layers: 2
  hidden_dim: 32
  final_dropout: 0.5
  learn_eps: false
  graph_pooling_type: sum
  neighbor_pooling_type: sum
  separate_embedding_layer: false
  data:
    class_path: sastvd.linevd.datamodule.BigVulDatasetLineVDDataModule
    init_args:
      feat: _ABS_DATAFLOW_datatype_all
      gtype: "cfg"
ckpt_path: null
