seed_everything: null
trainer:
  gpus: 1
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  max_epochs: 500
  weights_summary: top
  weights_save_path: null
  resume_from_checkpoint: null
  detect_anomaly: true
  gradient_clip_val: null
  accumulate_grad_batches: null
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
data:
  feat: _ABS_DATAFLOW_datatype_all
  gtype: "cfg"
model:
  num_layers: 5
  num_mlp_layers: 2
  hidden_dim: 32
  final_dropout: 0.5
  learn_eps: false
  graph_pooling_type: sum
  neighbor_pooling_type: sum
  separate_embedding_layer: false
ckpt_path: null
